# Generated by Django 5.2.13 on 2026-04-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='technical_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='vocabulary_score',
            field=models.FloatField(default=0),
        ),
    ]
