# Generated by Django 5.2.13 on 2026-04-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_answer_feedback_answer_technical_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_questions',
            field=models.IntegerField(default=5),
        ),
    ]
