# Generated by Django 5.2.13 on 2026-04-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_question_ai_model_used'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume'),
        ),
    ]
