# Generated by Django 5.2.13 on 2026-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interviewsession_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty_mode',
            field=models.CharField(default='beginner', max_length=20),
        ),
    ]
