# Generated by Django 5.2.13 on 2026-05-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interviewsession_difficulty_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='followup_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='domain',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='total_questions',
            field=models.IntegerField(default=15),
        ),
    ]
